### PR TITLE
New ActiveSync implementation

### PR DESCRIPTION
**Pull request by gsanchietti**
Old changes:

- Use PHP 71
- Configuration moved to webtop5-zpush package
- New wrapper for z-push-admin command

TODO:
- [x] Switch to PHP 7.2
- [x] Enable state.useLegacyFolderIds option (see https://github.com/sonicle-webtop/webtop-eas-server#requirements)

NethServer/dev#5732

### CODE REVIEW

**Comment by lucagasparini** [comment]
Information on the synchronized device is not shown.
The "Detailed Info" button executes this command: [see here](https://github.com/sonicle-webtop/webtop-core/blob/c76d66eb7978fa0cf5b28943c4dadf0ac1f23cd7/src/main/java/com/sonicle/webtop/core/util/ZPushManager.java#L114)
Complete composition of the command executed in the shell: [see here](https://github.com/sonicle-webtop/webtop-core/blob/c76d66eb7978fa0cf5b28943c4dadf0ac1f23cd7/src/main/java/com/sonicle/webtop/core/util/ZPushManager.java#L177)

**Comment by gsanchietti** [comment]
@lucagasparini the last build should fix the problem

**Comment by lucagasparini** [comment]
> @lucagasparini the last build should fix the problem

@gsanchietti I confirm that with the last build the problem is fixed 👍

**Comment by gsanchietti** [comment]
Waiting upstream for new working implementation.

**Pull request merged**
